export const bukhariBooks = [
  { id: 1, name: "Revelation", name_bn: "ওহীর সূচনা" },
  { id: 2, name: "Belief (Iman)", name_bn: "ঈমান" },
  { id: 3, name: "Knowledge", name_bn: "ইলম বা জ্ঞান" },
  { id: 4, name: "Ablution (Wudu')", name_bn: "ওযু" },
  { id: 5, name: "Bathing (Ghusl)", name_bn: "গোসল" },
  { id: 6, name: "Menstrual Periods", name_bn: "হায়েস" },
  { id: 7, name: "Rubbing hands and feet with dust (Tayammum)", name_bn: "তায়াম্মুম" },
  { id: 8, name: "Prayers (Salat)", name_bn: "সালাত" },
  { id: 9, name: "Virtues of the Prayer Hall (Sutra of the Musalla)", name_bn: "সালাতের ওয়াক্তসমূহ" },
  { id: 10, name: "Times of the Prayers", name_bn: "আযান" },
  { id: 11, name: "Call to Prayers (Adhaan)", name_bn: "জুমুআ" },
  { id: 12, name: "Friday Prayer", name_bn: "দুই ঈদের সালাত" },
  { id: 13, name: "The Two Festivals (Eids)", name_bn: "বিতর সালাত" },
  { id: 14, name: "Witr Prayer", name_bn: "বৃষ্টির জন্য দু’আ" },
  { id: 15, name: "Invoking Allah for Rain (Istisqaa)", name_bn: "সূর্যগ্রহণ" },
  { id: 16, name: "Eclipses", name_bn: "তিলাওয়াতের সিজদা" },
  { id: 17, name: "Prostration During Recital of Qur'an", name_bn: "সালাতে কসর করা" },
  { id: 18, name: "Shortening the Prayers (At-Taqseer)", name_bn: "তাহাজ্জুদ" },
  { id: 19, name: "Prayer at Night (Tahajjud)", name_bn: "মক্কা ও মদীনার মসজিদ" },
  { id: 20, name: "Virtues of Prayer at Masjid Makkah and Madinah", name_bn: "সালাতে আমল" },
  { id: 21, name: "Actions while Praying", name_bn: "সাহু সিজদা" },
  { id: 22, name: "Forgetfulness in Prayer", name_bn: "জানাযা" },
  { id: 23, name: "Funerals (Al-Janaa'iz)", name_bn: "যাকাত" },
  { id: 24, name: "Obligatory Charity Tax (Zakat)", name_bn: "হজ্জ" },
  { id: 25, name: "Hajj (Pilgrimage)", name_bn: "উমরাহ" },
  { id: 26, name: "Umrah (Minor pilgrimage)", name_bn: "মুহসার ও জাযা" },
  { id: 27, name: "Pilgrims Prevented from Completing the Pilgrimage", name_bn: "ইহরাম অবস্থায় শিকারের দণ্ড" },
  { id: 28, name: "Penalty of Hunting while on Pilgrimage", name_bn: "মদীনার ফযীলত" },
  { id: 29, name: "Virtues of Madinah", name_bn: "রোজা" },
  { id: 30, name: "Fasting (Saum)", name_bn: "তারাবীহ সালাত" },
  { id: 31, name: "Tarawih Prayers", name_bn: "লাইলাতুল কদর" },
  { id: 32, name: "Virtues of the Night of Qadr", name_bn: "ই’তিকাফ" },
  { id: 33, name: "Retiring to a Mosque for Remembrance (I'tikaf)", name_bn: "ক্রয়-বিক্রয়" },
  { id: 34, name: "Sales and Trade", name_bn: "সালাম বা অগ্রিম মূল্য" },
  { id: 35, name: "Sales in which a Price is paid for Goods to be Delivered Later (As-Salam)", name_bn: "ইজারা বা ভাড়ায় খাটানো" },
  { id: 36, name: "Hiring", name_bn: "হাওলা বা ঋণ স্থানান্তর" },
  { id: 37, name: "Transferance of a Debt from One Person to Another (Al-Hawaala)", name_bn: "কাফালা বা জামিনদার হওয়া" },
  { id: 38, name: "Representation, Authorization, Business by Proxy", name_bn: "ওয়াকালা বা প্রতিনিধি নিয়োগ" },
  { id: 39, name: "Agriculture", name_bn: "কৃষি ও চাষাবাদ" },
  { id: 40, name: "Distribution of Water", name_bn: "পানি সেচ ও বন্টন" },
  { id: 41, name: "Loans, Payment of Loans, Freezing of Property, Bankruptcy", name_bn: "ঋণ গ্রহণ ও পরিশোধ" },
  { id: 42, name: "Lost Things Picked up by Someone (Luqata)", name_bn: "লুকাতা বা কুড়িয়ে পাওয়া বস্তু" },
  { id: 43, name: "Oppressions", name_bn: "যুলুম ও কিসাস" },
  { id: 44, name: "Partnership", name_bn: "শির্কাত বা অংশীদারিত্ব" },
  { id: 45, name: "Mortgaging", name_bn: "বন্ধক" },
  { id: 46, name: "Manumission of Slaves", name_bn: "দাস আযাদ করা" },
  { id: 47, name: "Gifts", name_bn: "হেবা বা উপহার" },
  { id: 48, name: "Witnesses", name_bn: "শাহাদাত বা সাক্ষ্যদান" },
  { id: 49, name: "Peacemaking", name_bn: "সুলহ বা সন্ধি" },
  { id: 50, name: "Conditions", name_bn: "শুরুত বা শর্তাবলী" },
  { id: 51, name: "Wills and Testaments (Wasaayaa)", name_bn: "ওয়াসিয়াত" },
  { id: 52, name: "Fighting for the Cause of Allah (Jihad)", name_bn: "জিহাদ" },
  { id: 53, name: "One-fifth of Booty to the Cause of Allah (Khumus)", name_bn: "খুমুস বা এক-পঞ্চমাংশ" },
  { id: 54, name: "The Beginning of Creation", name_bn: "সৃষ্টির সূচনা" },
  { id: 55, name: "Prophets", name_bn: "নবীদের কাহিনী" },
  { id: 56, name: "Virtues and Merits of the Prophet (pbuh) and his Companions", name_bn: "সাহাবীদের ফযীলত" },
  { id: 57, name: "Companions of the Prophet", name_bn: "মদীনার আনসারগণ" },
  { id: 58, name: "Merits of the Helpers in Madinah (Ansaar)", name_bn: "মাগাযী বা যুদ্ধাভিযান" },
  { id: 59, name: "Military Expeditions led by the Prophet (pbuh) (Al-Maghaazi)", name_bn: "তাফসীর" },
  { id: 60, name: "Prophetic Commentary on the Qur'an (Tafseer)", name_bn: "কুরআনের ফযীলত" },
  { id: 61, name: "Virtues of the Qur'an", name_bn: "বিবাহ" },
  { id: 62, name: "Wedlock, Marriage (Nikaah)", name_bn: "তালাক" },
  { id: 63, name: "Divorce", name_bn: "ভরণপোষণ" },
  { id: 64, name: "Supporting the Family", name_bn: "পানীয়" },
  { id: 65, name: "Food, Meals", name_bn: "খাদ্যদ্রব্য" },
  { id: 66, name: "Sacrifice on Occasion of Birth (Aqiqah)", name_bn: "আকিকা" },
  { id: 67, name: "Hunting, Slaughtering", name_bn: "শিকার ও যবেহ" },
  { id: 68, name: "Al-Adha Festival Sacrifice (Adaahi)", name_bn: "কুরবানী" },
  { id: 69, name: "Drinks", name_bn: "পানীয়সমূহ" },
  { id: 70, name: "Patients", name_bn: "রোগী ও চিকিৎসা" },
  { id: 71, name: "Medicine", name_bn: "ঔষধ ও চিকিৎসা" },
  { id: 72, name: "Dress", name_bn: "পোশাক-পরিচ্ছদ" },
  { id: 73, name: "Good Manners and Form (Al-Adab)", name_bn: "আদব বা শিষ্টাচার" },
  { id: 74, name: "Asking Permission", name_bn: "অনুমতি প্রার্থনা" },
  { id: 75, name: "Invocations", name_bn: "দু’আসমূহ" },
  { id: 76, name: "To make the Heart Tender (Ar-Riqaq)", name_bn: "রিকাক বা মনগলানো কথা" },
  { id: 77, name: "Divine Will (Al-Qadar)", name_bn: "তাকদীর বা ভাগ্য" },
  { id: 78, name: "Oaths and Vows", name_bn: "শপথ ও মানত" },
  { id: 79, name: "Expiation for Unfulfilled Oaths", name_bn: "কাফফারা" },
  { id: 80, name: "Laws of Inheritance (Al-Faraa'id)", name_bn: "ফারায়েয বা উত্তরাধিকার" },
  { id: 81, name: "Limits and Punishments set by Allah (Hudood)", name_bn: "হুদুদ বা দণ্ডবিধি" },
  { id: 82, name: "Punishment of Disbelievers at War with Allah and His Apostle", name_bn: "মুরতাদের শাস্তি" },
  { id: 83, name: "Blood Money (Ad-Diyat)", name_bn: "দিয়াত বা রক্তপণ" },
  { id: 84, name: "Dealing with Apostates", name_bn: "বিদ্রোহীদের বিবরণ" },
  { id: 85, name: "Saying Something under Compulsion (Ikraah)", name_bn: "ইকরাহ বা বাধ্য করা" },
  { id: 86, name: "Tricks", name_bn: "হীলা বা কৌশল" },
  { id: 87, name: "Interpretation of Dreams", name_bn: "স্বপ্নের ব্যাখ্যা" },
  { id: 88, name: "Afflictions and the End of the World", name_bn: "ফিতনা বা বিশৃঙ্খলা" },
  { id: 89, name: "Judgments (Ahkaam)", name_bn: "আহকাম বা বিধান" },
  { id: 90, name: "Wishes", name_bn: "তামান্না বা আকাঙ্ক্ষা" },
  { id: 91, name: "Accepting Information Given by a Truthful Person", name_bn: "খবরে ওয়াহিদ" },
  { id: 92, name: "Holding Fast to the Qur'an and Sunnah", name_bn: "কিতাব ও সুন্নাহ আঁকড়ে ধরা" },
  { id: 93, name: "Oneness, Uniqueness of Allah (Tawheed)", name_bn: "তাওহীদ" }
];
// Note: Depending on edition, some merge books to 93, others split to 97. 
// This list covers the major sections used by standard APIs.