export const muslimBooks = [
  { id: 1, name: "Faith (Kitab Al Iman)", name_bn: "ঈমান" },
  { id: 2, name: "Purification (Kitab Al-Taharah)", name_bn: "পবিত্রতা" },
  { id: 3, name: "Menstruation (Kitab Al-Haid)", name_bn: "হায়েস" },
  { id: 4, name: "Prayers (Kitab Al-Salat)", name_bn: "সালাত" },
  { id: 5, name: "Mosques and Places of Prayer", name_bn: "মসজিদ ও সালাতের স্থান" },
  { id: 6, name: "Prayer - Travellers", name_bn: "মুসাফিরের সালাত" },
  { id: 7, name: "Friday Prayer", name_bn: "জুমুআ" },
  { id: 8, name: "Prayer - Two Eids", name_bn: "দুই ঈদের সালাত" },
  { id: 9, name: "Prayer - Rain (Istisqa)", name_bn: "বৃষ্টির জন্য দু’আ" },
  { id: 10, name: "Prayer - Eclipses", name_bn: "সূর্যগ্রহণ" },
  { id: 11, name: "Prayer - Funerals", name_bn: "জানাযা" },
  { id: 12, name: "Zakat (Kitab Al-Zakat)", name_bn: "যাকাত" },
  { id: 13, name: "Fasting (Kitab Al-Sawm)", name_bn: "সিয়াম বা রোজা" },
  { id: 14, name: "I'tikaf", name_bn: "ই’তিকাফ" },
  { id: 15, name: "Pilgrimage (Hajj)", name_bn: "হজ্জ" },
  { id: 16, name: "Marriage (Kitab Al-Nikah)", name_bn: "বিবাহ" },
  { id: 17, name: "Suckling (Kitab Al-Rada)", name_bn: "দুগ্ধপান" },
  { id: 18, name: "Divorce (Kitab Al-Talaq)", name_bn: "তালাক" },
  { id: 19, name: "Cursing (Li'an)", name_bn: "লি'আন" },
  { id: 20, name: "Emancipation (Itq)", name_bn: "দাসমুক্তি" },
  { id: 21, name: "Business Transactions", name_bn: "ক্রয়-বিক্রয়" },
  { id: 22, name: "Inheritance (Fara'id)", name_bn: "উত্তরাধিকার" },
  { id: 23, name: "Gifts (Al-Hiba)", name_bn: "দান" },
  { id: 24, name: "Wills (Wasiyya)", name_bn: "ওসিয়ত" },
  { id: 25, name: "Vows (Nadr)", name_bn: "মানত" },
  { id: 26, name: "Oaths (Aiman)", name_bn: "কসম" },
  { id: 27, name: "Oaths, Establishing Responsibility for Murders, Fighting, Requital", name_bn: "কসম ও কাসামা" },
  { id: 28, name: "Method of Punishment (Qasamah)", name_bn: "হুদুদ বা দণ্ডবিধি" },
  { id: 29, name: "Judicial Decisions", name_bn: "বিচার ফয়সালা" },
  { id: 30, name: "Lost Property", name_bn: "হারানো বস্তু" },
  { id: 31, name: "Jihad and Expedition", name_bn: "জিহাদ ও সফর" },
  { id: 32, name: "Government", name_bn: "নেতৃত্ব ও প্রশাসন" },
  { id: 33, name: "Hunting and Slaughter", name_bn: "শিকার ও জবাই" },
  { id: 34, name: "Sacrifices", name_bn: "কুরবানী" },
  { id: 35, name: "Drinks", name_bn: "পানীয়" },
  { id: 36, name: "Clothes and Decoration", name_bn: "পোশাক ও সাজসজ্জা" },
  { id: 37, name: "General Behavior (Adab)", name_bn: "আদব-কায়দা" },
  { id: 38, name: "Greetings and Salutations", name_bn: "সালাম" },
  { id: 39, name: "Peace", name_bn: "শান্তি" },
  { id: 40, name: "Poetry", name_bn: "কবিতা" },
  { id: 41, name: "Vision (Dreams)", name_bn: "স্বপ্ন" },
  { id: 42, name: "Virtues", name_bn: "ফযিলত" },
  { id: 43, name: "Merits of the Companions", name_bn: "সাহাবীদের মর্যাদা" },
  { id: 44, name: "Virtue, Good Manners and Joining of the Ties of Relationship", name_bn: "সদাচরণ ও আত্মীয়তা" },
  { id: 45, name: "Destiny (Qadr)", name_bn: "তাকদীর" },
  { id: 46, name: "Knowledge (Ilm)", name_bn: "ইলম" },
  { id: 47, name: "Dhikr, Supplication, Repentance", name_bn: "যিকির, দুআ, তওবা" },
  { id: 48, name: "Heart Melting Traditions", name_bn: "রিকাক (হৃদয় গলানো)" },
  { id: 49, name: "Repentance", name_bn: "তওবা কবুল" },
  { id: 50, name: "Characteristics of Hypocrites", name_bn: "মুনাফিকের বৈশিষ্ট্য" },
  { id: 51, name: "Giving Description of the Day of Judgment, Paradise and Hell", name_bn: "কিয়ামত, জান্নাত, জাহান্নাম" },
  { id: 52, name: "Paradise, its Description, its Bounties and its Inhabitants", name_bn: "জান্নাতের বর্ণনা" },
  { id: 53, name: "Tribulations and Portents of the Last Hour", name_bn: "ফিতনা ও কিয়ামতের আলামত" },
  { id: 54, name: "Asceticism and Softening of Hearts", name_bn: "যুহদ (পৃথিবী বিমুখতা)" },
  { id: 55, name: "Tafsir (Exegesis)", name_bn: "তাফসীর" }
];